apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 9router
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/HaPhanBaoMinh/ai-agent.git
    targetRevision: main
    path: charts/9router
    helm:
      releaseName: 9router
      valueFiles:
        - values-minikube.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
