apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama-deepseek-r1
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/HaPhanBaoMinh/ai-agent.git
    targetRevision: main
    path: charts/ollama
    helm:
      releaseName: ollama-deepseek-r1
      valueFiles:
        - values-deepseek-r1.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
