apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama-models
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/HaPhanBaoMinh/ai-agent.git
    targetRevision: main
    path: charts/ollama-models
    helm:
      releaseName: ollama-models-gemma3
      valueFiles:
        - values-gemma3.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
