enabled: true

image:
  repository: ollama/ollama
  tag: latest
  pullPolicy: IfNotPresent

ollamaUrl: http://ollama-gemma3.ai-platform.svc.cluster.local:11434

models:
  - gemma3:4b

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 4Gi

backoffLimit: 2
activeDeadlineSeconds: 14400
