enabled: true

routerUrl: http://nine-router.ai-platform.svc.cluster.local:20128

auth:
  existingSecret: ""
  passwordKey: ADMIN_PASSWORD
  allowDefaultPassword: true
  defaultPassword: "123456"

providerSecrets:
  existingSecret: 9router-provider-secrets

providers:
  - name: Ollama Local
    provider: ollama-local
    enabled: true
    priority: 1
    defaultModel: qwen2.5-coder:3b
    providerSpecificData:
      baseUrl: http://ollama-qwen-coder.ai-platform.svc.cluster.local.:11434
  - name: Gemini API
    provider: gemini
    enabled: true
    apiKeyEnv: GEMINI_API_KEY
    priority: 20
    defaultModel: gemini-2.5-flash
  - name: OpenRouter
    provider: openrouter
    enabled: true
    apiKeyEnv: OPENROUTER_API_KEY
    priority: 30
    defaultModel: free
  - name: OpenAI API
    provider: openai
    enabled: false
    apiKeyEnv: OPENAI_API_KEY
    priority: 40
  - name: Groq
    provider: groq
    enabled: false
    apiKeyEnv: GROQ_API_KEY
    priority: 50

customProviderNodes: []

aliases:
  - alias: local-coder
    model: ollama-local/qwen2.5-coder:3b
  - alias: gemini-flash
    model: gemini/gemini-2.5-flash
  - alias: openrouter-free
    model: openrouter/free
