{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-secret" (include "9router.fullname" .)) .Values.secret.existingSecret }}
  labels:
    {{- include "9router.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.apiKeyName }}: replace-me
{{- end }}
